name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake GIF
        uses: Platane/snk@v3
        with:
          github_user_name: sandhyaasingh
          outputs: dist/github-snake.svg
          
      - name: Push Snake GIF to the repo
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
